# Basic
title: Seeyong's Blog
author: Seeyong
description: CFA Charterholder , Data Scientist , Editor<br/>live in Seoul

url: "https://brunch.co.kr/@seeyonglee"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# Pagination
gems: [jekyll-paginate]
paginate: 15
paginate_path: "pages/:num/"

# Social
social:
    instagram: be_seeyong
    github: Seeyong
    gplus: 112547382138552250597
    mail: seeyong987@gmail.com
